### PR TITLE
add kue to the list

### PR DESCRIPTION
**Pull request by behrad**
Most popular distributed priority queue's name in node.js was missing...

### CODE REVIEW

**Comment by strzalek** [comment]
Sorry guys.

@behrad mind rebasing? I'll happily merge this PR.

**Comment by behrad** [comment]
nice to here from you @strzalek eagerly waiting for merge :)

**Comment by strzalek** [comment]
Sure, you'd need to rebase branch against master, could you do that?

**Comment by behrad** [comment]
yes, i will rebase and let you know @strzalek

**Comment by nemo** [comment]
+1 :)

**Comment by behrad** [comment]
WoW, totally blew this... @strzalek I'll rebase in days and let you know.

**Comment by behrad** [comment]
closing in favor of #89 , expecting @strzalek to merge, thank you

**Pull request closed without merging**
